services:
  - type: web
    name: pharmai-backend
    env: python
    runtime: python-3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000