"""Curated dataset generator: 2000+ unique medicines without dosage-duplicates.

A "medicine" is uniquely defined by (substance, manufacturer, brand).
Different dosages of the same brand live in `variants` — never as new rows.
"""
from typing import List, Dict

# ----- pharmacies (informational only) -----
PHARMACY_NAMES = [
    "Natali Pharm", "Alfa Pharm", "City Pharm", "Med Pharm",
    "Pharm Eskulap", "Sirena", "Erevan Pharm", "ArmPharm",
    "Salud", "Vita", "Halve", "Optima", "Garni Pharm",
    "Sevan Pharm", "Aragats Pharm", "Health Plus",
]

# Substance dictionary: substance_inn -> {category, name_hy, name_ru, name_en, desc, ind, side, contra, dosages[], forms[]}
SUBSTANCES: List[Dict] = [
    # Painkillers / NSAID
    {"sub": "Paracetamol", "cat": "painkillers",
     "hy": "Պարացետամոլ", "ru": "Парацетамол", "en": "Paracetamol",
     "desc": {"en": "Analgesic and antipyretic.", "ru": "Анальгетик и жаропонижающее.", "hy": "Ցավազրկող և ջերմիջեցնող։"},
     "ind": {"en": "Pain, fever.", "ru": "Боль, жар.", "hy": "Ցավ, ջերմություն։"},
     "side": ["Rare: rash"], "contra": ["Severe liver disease"],
     "dosages": ["200 mg", "325 mg", "500 mg", "1000 mg"],
     "forms": ["tablet", "syrup", "suppository"]},
    {"sub": "Ibuprofen", "cat": "painkillers",
     "hy": "Իբուպրոֆեն", "ru": "Ибупрофен", "en": "Ibuprofen",
     "desc": {"en": "NSAID — pain, inflammation, fever.", "ru": "НПВС — боль, воспаление, жар.", "hy": "ՈՒՀՀԴ — ցավ, բորբոքում։"},
     "ind": {"en": "Pain, inflammation, fever.", "ru": "Боль, воспаление, лихорадка.", "hy": "Ցավ, բորբոքում, ջերմություն։"},
     "side": ["GI discomfort", "Dizziness"], "contra": ["Active ulcer", "Severe renal failure"],
     "dosages": ["200 mg", "400 mg", "600 mg"], "forms": ["tablet", "capsule", "suspension"]},
    {"sub": "Aspirin", "cat": "painkillers",
     "hy": "Ասպիրին", "ru": "Аспирин", "en": "Aspirin",
     "desc": {"en": "Acetylsalicylic acid.", "ru": "Ацетилсалициловая кислота.", "hy": "Ացետիլսալիցիլաթթու։"},
     "ind": {"en": "Pain, fever, antiplatelet.", "ru": "Боль, жар, антиагрегант.", "hy": "Ցավ, ջերմություն։"},
     "side": ["GI bleeding"], "contra": ["Children with viral infections"],
     "dosages": ["75 mg", "100 mg", "500 mg"], "forms": ["tablet"]},
    {"sub": "Diclofenac", "cat": "painkillers",
     "hy": "Դիկլոֆենակ", "ru": "Диклофенак", "en": "Diclofenac",
     "desc": {"en": "NSAID for musculoskeletal pain.", "ru": "НПВС.", "hy": "ՈՒՀՀԴ։"},
     "ind": {"en": "Arthritis, back pain.", "ru": "Артрит, боль в спине.", "hy": "Հոդաբորբ։"},
     "side": ["GI upset"], "contra": ["Peptic ulcer"],
     "dosages": ["25 mg", "50 mg", "75 mg", "100 mg"], "forms": ["tablet", "gel", "injection"]},
    {"sub": "Ketoprofen", "cat": "painkillers",
     "hy": "Կետոպրոֆեն", "ru": "Кетопрофен", "en": "Ketoprofen",
     "desc": {"en": "NSAID.", "ru": "НПВС.", "hy": "ՈՒՀՀԴ։"},
     "ind": {"en": "Pain, inflammation.", "ru": "Боль, воспаление.", "hy": "Ցավ։"},
     "side": ["GI upset"], "contra": ["Ulcer"],
     "dosages": ["50 mg", "100 mg"], "forms": ["capsule", "gel"]},
    {"sub": "Naproxen", "cat": "painkillers",
     "hy": "Նապրոքսեն", "ru": "Напроксен", "en": "Naproxen",
     "desc": {"en": "Long-acting NSAID.", "ru": "НПВС длительного действия.", "hy": "Երկարատև ՈՒՀՀԴ։"},
     "ind": {"en": "Arthritis, dysmenorrhea.", "ru": "Артрит.", "hy": "Հոդաբորբ։"},
     "side": ["GI upset"], "contra": ["Ulcer"],
     "dosages": ["220 mg", "275 mg", "500 mg"], "forms": ["tablet"]},
    {"sub": "Nimesulide", "cat": "painkillers",
     "hy": "Նիմեսուլիդ", "ru": "Нимесулид", "en": "Nimesulide",
     "desc": {"en": "Selective COX-2 NSAID.", "ru": "Селективный НПВС.", "hy": "Ընտրողական ՈՒՀՀԴ։"},
     "ind": {"en": "Acute pain.", "ru": "Острая боль.", "hy": "Սուր ցավ։"},
     "side": ["Liver enzyme elevation"], "contra": ["Liver disease"],
     "dosages": ["100 mg"], "forms": ["tablet", "granules"]},
    {"sub": "Metamizole", "cat": "painkillers",
     "hy": "Անալգին", "ru": "Анальгин", "en": "Metamizole",
     "desc": {"en": "Non-opioid analgesic.", "ru": "Анальгетик.", "hy": "Ցավազրկող։"},
     "ind": {"en": "Acute pain, fever.", "ru": "Боль, жар.", "hy": "Ցավ, ջերմություն։"},
     "side": ["Rare agranulocytosis"], "contra": ["Pregnancy 3rd trimester"],
     "dosages": ["500 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Ketorolac", "cat": "painkillers",
     "hy": "Կետորոլակ", "ru": "Кеторолак", "en": "Ketorolac",
     "desc": {"en": "Potent NSAID for short-term use.", "ru": "Сильный НПВС.", "hy": "Հզոր ՈՒՀՀԴ։"},
     "ind": {"en": "Postoperative pain.", "ru": "Послеоперационная боль.", "hy": "Հետվիրահատական ցավ։"},
     "side": ["GI bleeding"], "contra": ["Renal failure"],
     "dosages": ["10 mg", "30 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Meloxicam", "cat": "painkillers",
     "hy": "Մելոքսիկամ", "ru": "Мелоксикам", "en": "Meloxicam",
     "desc": {"en": "NSAID.", "ru": "НПВС.", "hy": "ՈՒՀՀԴ։"},
     "ind": {"en": "Osteoarthritis.", "ru": "Остеоартроз.", "hy": "Օստեոարթրոզ։"},
     "side": ["GI upset"], "contra": ["Ulcer"],
     "dosages": ["7.5 mg", "15 mg"], "forms": ["tablet"]},

    # Antibiotics
    {"sub": "Amoxicillin", "cat": "antibiotics",
     "hy": "Ամոքսիցիլին", "ru": "Амоксициллин", "en": "Amoxicillin",
     "desc": {"en": "Penicillin antibiotic.", "ru": "Пенициллиновый антибиотик.", "hy": "Պենիցիլինային հակաբիոտիկ։"},
     "ind": {"en": "Bacterial infections.", "ru": "Бактериальные инфекции.", "hy": "Բակտերիալ վարակներ։"},
     "side": ["Diarrhea", "Rash"], "contra": ["Penicillin allergy"],
     "dosages": ["250 mg", "500 mg", "875 mg", "1000 mg"], "forms": ["capsule", "suspension"]},
    {"sub": "Azithromycin", "cat": "antibiotics",
     "hy": "Ազիտրոմիցին", "ru": "Азитромицин", "en": "Azithromycin",
     "desc": {"en": "Macrolide antibiotic.", "ru": "Макролид.", "hy": "Մակրոլիդ։"},
     "ind": {"en": "Respiratory infections.", "ru": "Респираторные инфекции.", "hy": "Շնչուղիների վարակներ։"},
     "side": ["GI upset"], "contra": ["Liver dysfunction"],
     "dosages": ["250 mg", "500 mg"], "forms": ["tablet", "suspension"]},
    {"sub": "Ciprofloxacin", "cat": "antibiotics",
     "hy": "Ցիպրոֆլոքսացին", "ru": "Ципрофлоксацин", "en": "Ciprofloxacin",
     "desc": {"en": "Fluoroquinolone.", "ru": "Фторхинолон.", "hy": "Ֆտորքինոլոն։"},
     "ind": {"en": "UTI, GI infections.", "ru": "Инфекции мочевых путей.", "hy": "Միզուղիների վարակ։"},
     "side": ["Tendinopathy"], "contra": ["Pregnancy", "Under 18"],
     "dosages": ["250 mg", "500 mg", "750 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Doxycycline", "cat": "antibiotics",
     "hy": "Դոքսիցիկլին", "ru": "Доксициклин", "en": "Doxycycline",
     "desc": {"en": "Tetracycline antibiotic.", "ru": "Тетрациклин.", "hy": "Տետրացիկլին։"},
     "ind": {"en": "Respiratory, skin infections.", "ru": "Респираторные инфекции.", "hy": "Շնչուղիների վարակ։"},
     "side": ["Photosensitivity"], "contra": ["Pregnancy", "Children <8"],
     "dosages": ["100 mg"], "forms": ["capsule"]},
    {"sub": "Clarithromycin", "cat": "antibiotics",
     "hy": "Կլարիտրոմիցին", "ru": "Кларитромицин", "en": "Clarithromycin",
     "desc": {"en": "Macrolide.", "ru": "Макролид.", "hy": "Մակրոլիդ։"},
     "ind": {"en": "Respiratory, H.pylori.", "ru": "Респираторные инфекции.", "hy": "Շնչուղի։"},
     "side": ["Taste disturbance"], "contra": ["Liver disease"],
     "dosages": ["250 mg", "500 mg"], "forms": ["tablet"]},
    {"sub": "Cefuroxime", "cat": "antibiotics",
     "hy": "Ցեֆուրոքսիմ", "ru": "Цефуроксим", "en": "Cefuroxime",
     "desc": {"en": "2nd-gen cephalosporin.", "ru": "Цефалоспорин II.", "hy": "Ցեֆալոսպորին։"},
     "ind": {"en": "Respiratory, urinary infections.", "ru": "Инфекции.", "hy": "Վարակ։"},
     "side": ["Diarrhea"], "contra": ["Cephalosporin allergy"],
     "dosages": ["250 mg", "500 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Ceftriaxone", "cat": "antibiotics",
     "hy": "Ցեֆտրիաքսոն", "ru": "Цефтриаксон", "en": "Ceftriaxone",
     "desc": {"en": "3rd-gen cephalosporin.", "ru": "Цефалоспорин III.", "hy": "Ցեֆալոսպորին III։"},
     "ind": {"en": "Severe bacterial infections.", "ru": "Тяжёлые инфекции.", "hy": "Ծանր վարակ։"},
     "side": ["Injection site pain"], "contra": ["Allergy"],
     "dosages": ["500 mg", "1000 mg", "2000 mg"], "forms": ["injection"]},
    {"sub": "Amoxiclav", "cat": "antibiotics",
     "hy": "Ամոքսիկլավ", "ru": "Амоксиклав", "en": "Amoxicillin/Clavulanate",
     "desc": {"en": "Amoxicillin + beta-lactamase inhibitor.", "ru": "Амоксициллин + клавуланат.", "hy": "Ամոքսիցիլին + կլավուլանատ։"},
     "ind": {"en": "Bacterial infections.", "ru": "Инфекции.", "hy": "Վարակ։"},
     "side": ["Diarrhea"], "contra": ["Penicillin allergy"],
     "dosages": ["375 mg", "625 mg", "1000 mg"], "forms": ["tablet", "suspension"]},
    {"sub": "Metronidazole", "cat": "antibiotics",
     "hy": "Մետրոնիդազոլ", "ru": "Метронидазол", "en": "Metronidazole",
     "desc": {"en": "Antiprotozoal/antibacterial.", "ru": "Антипротозойное.", "hy": "Հակամակաբույծային։"},
     "ind": {"en": "Anaerobic infections.", "ru": "Анаэробные инфекции.", "hy": "Անաէրոբ վարակ։"},
     "side": ["Metallic taste"], "contra": ["1st trimester pregnancy"],
     "dosages": ["250 mg", "500 mg"], "forms": ["tablet", "gel"]},
    {"sub": "Levofloxacin", "cat": "antibiotics",
     "hy": "Լևոֆլոքսացին", "ru": "Левофлоксацин", "en": "Levofloxacin",
     "desc": {"en": "Fluoroquinolone.", "ru": "Фторхинолон.", "hy": "Ֆտորքինոլոն։"},
     "ind": {"en": "Respiratory infections.", "ru": "Респираторные инфекции.", "hy": "Շնչուղի։"},
     "side": ["Tendinopathy"], "contra": ["Children <18"],
     "dosages": ["250 mg", "500 mg", "750 mg"], "forms": ["tablet"]},

    # Allergy
    {"sub": "Loratadine", "cat": "allergy",
     "hy": "Լորատադին", "ru": "Лоратадин", "en": "Loratadine",
     "desc": {"en": "Antihistamine.", "ru": "Антигистамин.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergic rhinitis, urticaria.", "ru": "Аллергический ринит.", "hy": "Ալերգիկ ռինիտ։"},
     "side": ["Mild drowsiness"], "contra": ["Hypersensitivity"],
     "dosages": ["5 mg", "10 mg"], "forms": ["tablet", "syrup"]},
    {"sub": "Cetirizine", "cat": "allergy",
     "hy": "Ցետիրիզին", "ru": "Цетиризин", "en": "Cetirizine",
     "desc": {"en": "Antihistamine.", "ru": "Антигистамин.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergies.", "ru": "Аллергии.", "hy": "Ալերգիա։"},
     "side": ["Drowsiness"], "contra": ["Severe renal disease"],
     "dosages": ["5 mg", "10 mg"], "forms": ["tablet", "drops"]},
    {"sub": "Desloratadine", "cat": "allergy",
     "hy": "Դեսլորատադին", "ru": "Дезлоратадин", "en": "Desloratadine",
     "desc": {"en": "Antihistamine.", "ru": "Антигистамин.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergic rhinitis.", "ru": "Ринит.", "hy": "Ռինիտ։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["2.5 mg", "5 mg"], "forms": ["tablet", "syrup"]},
    {"sub": "Fexofenadine", "cat": "allergy",
     "hy": "Ֆեքսոֆենադին", "ru": "Фексофенадин", "en": "Fexofenadine",
     "desc": {"en": "Non-sedating antihistamine.", "ru": "Антигистамин.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergies.", "ru": "Аллергии.", "hy": "Ալերգիա։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["120 mg", "180 mg"], "forms": ["tablet"]},
    {"sub": "Chloropyramine", "cat": "allergy",
     "hy": "Սուպրաստին", "ru": "Супрастин", "en": "Chloropyramine",
     "desc": {"en": "1st-gen antihistamine.", "ru": "Антигистамин I.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergic reactions.", "ru": "Аллергии.", "hy": "Ալերգիա։"},
     "side": ["Drowsiness"], "contra": ["Glaucoma"],
     "dosages": ["25 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Levocetirizine", "cat": "allergy",
     "hy": "Լևոցետիրիզին", "ru": "Левоцетиризин", "en": "Levocetirizine",
     "desc": {"en": "Antihistamine.", "ru": "Антигистамин.", "hy": "Հակահիստամին։"},
     "ind": {"en": "Allergies.", "ru": "Аллергии.", "hy": "Ալերգիա։"},
     "side": ["Drowsiness"], "contra": ["Renal failure"],
     "dosages": ["5 mg"], "forms": ["tablet", "drops"]},

    # Cold & Flu
    {"sub": "Oseltamivir", "cat": "cold",
     "hy": "Օսելտամիվիր", "ru": "Осельтамивир", "en": "Oseltamivir",
     "desc": {"en": "Antiviral for influenza.", "ru": "Противовирусное.", "hy": "Հակավիրուսային։"},
     "ind": {"en": "Influenza A/B.", "ru": "Грипп.", "hy": "Գրիպ։"},
     "side": ["Nausea"], "contra": ["Renal failure"],
     "dosages": ["30 mg", "45 mg", "75 mg"], "forms": ["capsule"]},
    {"sub": "Phenylephrine", "cat": "cold",
     "hy": "Ֆենիլեֆրին", "ru": "Фенилэфрин", "en": "Phenylephrine",
     "desc": {"en": "Decongestant.", "ru": "Деконгестант.", "hy": "Հակագերտածման։"},
     "ind": {"en": "Nasal congestion.", "ru": "Заложенность носа.", "hy": "Քթի փակվածություն։"},
     "side": ["Hypertension"], "contra": ["Hypertension"],
     "dosages": ["10 mg"], "forms": ["tablet", "spray"]},
    {"sub": "Pseudoephedrine", "cat": "cold",
     "hy": "Պսևդոէֆեդրին", "ru": "Псевдоэфедрин", "en": "Pseudoephedrine",
     "desc": {"en": "Decongestant.", "ru": "Деконгестант.", "hy": "Հակագերտածման։"},
     "ind": {"en": "Cold symptoms.", "ru": "Симптомы простуды.", "hy": "Մրսածության նշաններ։"},
     "side": ["Insomnia"], "contra": ["Hypertension"],
     "dosages": ["30 mg", "60 mg"], "forms": ["tablet"]},
    {"sub": "Xylometazoline", "cat": "cold",
     "hy": "Քսիլոմետազոլին", "ru": "Ксилометазолин", "en": "Xylometazoline",
     "desc": {"en": "Nasal decongestant.", "ru": "Сосудосуживающее.", "hy": "Քթային։"},
     "ind": {"en": "Nasal congestion.", "ru": "Насморк.", "hy": "Քթի փակվածություն։"},
     "side": ["Nasal irritation"], "contra": ["Glaucoma"],
     "dosages": ["0.05%", "0.1%"], "forms": ["spray", "drops"]},
    {"sub": "Acetylcysteine", "cat": "cold",
     "hy": "Ացետիլցիստեին", "ru": "Ацетилцистеин", "en": "Acetylcysteine",
     "desc": {"en": "Mucolytic.", "ru": "Муколитик.", "hy": "Մուկոլիտիկ։"},
     "ind": {"en": "Productive cough.", "ru": "Влажный кашель.", "hy": "Թաց հազ։"},
     "side": ["GI upset"], "contra": ["Active ulcer"],
     "dosages": ["100 mg", "200 mg", "600 mg"], "forms": ["effervescent tablet", "granules"]},
    {"sub": "Ambroxol", "cat": "cold",
     "hy": "Ամբրոքսոլ", "ru": "Амброксол", "en": "Ambroxol",
     "desc": {"en": "Expectorant.", "ru": "Отхаркивающее.", "hy": "Խորխաբեր։"},
     "ind": {"en": "Cough with sputum.", "ru": "Кашель.", "hy": "Հազ։"},
     "side": ["Nausea"], "contra": ["1st trimester pregnancy"],
     "dosages": ["30 mg", "75 mg"], "forms": ["tablet", "syrup"]},
    {"sub": "Bromhexine", "cat": "cold",
     "hy": "Բրոմհեքսին", "ru": "Бромгексин", "en": "Bromhexine",
     "desc": {"en": "Expectorant.", "ru": "Отхаркивающее.", "hy": "Խորխաբեր։"},
     "ind": {"en": "Productive cough.", "ru": "Кашель.", "hy": "Հազ։"},
     "side": ["GI upset"], "contra": ["Ulcer"],
     "dosages": ["8 mg", "16 mg"], "forms": ["tablet", "syrup"]},

    # Vitamins
    {"sub": "Vitamin C", "cat": "vitamins",
     "hy": "Վիտամին C", "ru": "Витамин C", "en": "Ascorbic acid",
     "desc": {"en": "Ascorbic acid.", "ru": "Аскорбиновая кислота.", "hy": "Ասկորբինաթթու։"},
     "ind": {"en": "Vitamin C deficiency.", "ru": "Дефицит витамина С.", "hy": "Վիտամին C-ի պակասուրդ։"},
     "side": ["GI upset at high doses"], "contra": ["Oxalate stones"],
     "dosages": ["100 mg", "500 mg", "1000 mg"], "forms": ["tablet", "effervescent tablet"]},
    {"sub": "Vitamin D3", "cat": "vitamins",
     "hy": "Վիտամին D3", "ru": "Витамин D3", "en": "Cholecalciferol",
     "desc": {"en": "Cholecalciferol.", "ru": "Холекальциферол.", "hy": "Խոլեկալցիֆերոլ։"},
     "ind": {"en": "Vitamin D deficiency.", "ru": "Дефицит витамина D.", "hy": "Դեֆիցիտ։"},
     "side": ["Hypercalcemia at overdose"], "contra": ["Hypercalcemia"],
     "dosages": ["400 IU", "1000 IU", "2000 IU", "5000 IU"], "forms": ["tablet", "drops", "capsule"]},
    {"sub": "Vitamin B12", "cat": "vitamins",
     "hy": "Վիտամին B12", "ru": "Витамин B12", "en": "Cyanocobalamin",
     "desc": {"en": "Cyanocobalamin.", "ru": "Цианокобаламин.", "hy": "Ցիանոկոբալամին։"},
     "ind": {"en": "B12 deficiency.", "ru": "Дефицит B12.", "hy": "Դեֆիցիտ։"},
     "side": ["Rare allergic reaction"], "contra": ["Hypersensitivity"],
     "dosages": ["500 mcg", "1000 mcg"], "forms": ["tablet", "injection"]},
    {"sub": "Folic acid", "cat": "vitamins",
     "hy": "Ֆոլաթթու", "ru": "Фолиевая кислота", "en": "Folic acid",
     "desc": {"en": "Vitamin B9.", "ru": "Витамин B9.", "hy": "Վիտամին B9։"},
     "ind": {"en": "Pregnancy, anemia.", "ru": "Беременность.", "hy": "Հղիություն։"},
     "side": ["Rare allergy"], "contra": ["Hypersensitivity"],
     "dosages": ["400 mcg", "1 mg", "5 mg"], "forms": ["tablet"]},
    {"sub": "Multivitamin", "cat": "vitamins",
     "hy": "Մուլտիվիտամին", "ru": "Мультивитамин", "en": "Multivitamin",
     "desc": {"en": "Combined vitamin and mineral complex.", "ru": "Витамины и минералы.", "hy": "Վիտամինների համալիր։"},
     "ind": {"en": "Vitamin/mineral supplementation.", "ru": "Дефицит витаминов.", "hy": "Դեֆիցիտ։"},
     "side": ["Mild GI upset"], "contra": ["Hypervitaminosis"],
     "dosages": ["adult", "senior", "kids"], "forms": ["tablet", "capsule", "syrup"]},
    {"sub": "Magnesium B6", "cat": "vitamins",
     "hy": "Մագնեզիում B6", "ru": "Магний B6", "en": "Magnesium B6",
     "desc": {"en": "Magnesium with pyridoxine.", "ru": "Магний с B6.", "hy": "Մագնեզիում B6։"},
     "ind": {"en": "Magnesium deficiency.", "ru": "Дефицит магния.", "hy": "Մագնեզիումի պակաս։"},
     "side": ["Loose stool"], "contra": ["Renal failure"],
     "dosages": ["48 mg", "100 mg"], "forms": ["tablet", "ampoule"]},
    {"sub": "Iron sulfate", "cat": "vitamins",
     "hy": "Երկաթ", "ru": "Железо", "en": "Iron sulfate",
     "desc": {"en": "Iron supplement.", "ru": "Препарат железа.", "hy": "Երկաթի պատրաստուկ։"},
     "ind": {"en": "Iron-deficiency anemia.", "ru": "ЖДА.", "hy": "Անեմիա։"},
     "side": ["Constipation"], "contra": ["Hemochromatosis"],
     "dosages": ["100 mg", "200 mg", "325 mg"], "forms": ["tablet", "syrup"]},
    {"sub": "Calcium D3", "cat": "vitamins",
     "hy": "Կալցիում D3", "ru": "Кальций D3", "en": "Calcium D3",
     "desc": {"en": "Calcium with vitamin D3.", "ru": "Кальций + D3.", "hy": "Կալցիում + D3։"},
     "ind": {"en": "Osteoporosis prevention.", "ru": "Профилактика остеопороза.", "hy": "Օստեոպորոզ։"},
     "side": ["Constipation"], "contra": ["Hypercalcemia"],
     "dosages": ["500 mg", "600 mg"], "forms": ["tablet", "chewable"]},
    {"sub": "Omega-3", "cat": "vitamins",
     "hy": "Օմեգա-3", "ru": "Омега-3", "en": "Omega-3",
     "desc": {"en": "Fish-oil fatty acids.", "ru": "Жирные кислоты.", "hy": "Ձկան յուղ։"},
     "ind": {"en": "Supplementation.", "ru": "БАД.", "hy": "Հավելում։"},
     "side": ["Fishy aftertaste"], "contra": ["Hypersensitivity"],
     "dosages": ["500 mg", "1000 mg"], "forms": ["capsule"]},

    # Cardiovascular
    {"sub": "Bisoprolol", "cat": "cardio",
     "hy": "Բիսոպրոլոլ", "ru": "Бисопролол", "en": "Bisoprolol",
     "desc": {"en": "Beta-1 blocker.", "ru": "Бета-блокатор.", "hy": "Բետա-բլոկատոր։"},
     "ind": {"en": "Hypertension, heart failure.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Bradycardia"], "contra": ["AV block"],
     "dosages": ["2.5 mg", "5 mg", "10 mg"], "forms": ["tablet"]},
    {"sub": "Amlodipine", "cat": "cardio",
     "hy": "Ամլոդիպին", "ru": "Амлодипин", "en": "Amlodipine",
     "desc": {"en": "Calcium channel blocker.", "ru": "Антагонист кальция.", "hy": "Կալցիումի անցուղիների։"},
     "ind": {"en": "Hypertension.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Ankle edema"], "contra": ["Severe hypotension"],
     "dosages": ["5 mg", "10 mg"], "forms": ["tablet"]},
    {"sub": "Lisinopril", "cat": "cardio",
     "hy": "Լիզինոպրիլ", "ru": "Лизиноприл", "en": "Lisinopril",
     "desc": {"en": "ACE inhibitor.", "ru": "Ингибитор АПФ.", "hy": "ԱՊՖ արգելակիչ։"},
     "ind": {"en": "Hypertension, heart failure.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Dry cough"], "contra": ["Pregnancy"],
     "dosages": ["5 mg", "10 mg", "20 mg"], "forms": ["tablet"]},
    {"sub": "Losartan", "cat": "cardio",
     "hy": "Լոսարտան", "ru": "Лозартан", "en": "Losartan",
     "desc": {"en": "ARB.", "ru": "БРА.", "hy": "ԱԲ։"},
     "ind": {"en": "Hypertension.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Dizziness"], "contra": ["Pregnancy"],
     "dosages": ["25 mg", "50 mg", "100 mg"], "forms": ["tablet"]},
    {"sub": "Atorvastatin", "cat": "cardio",
     "hy": "Ատորվաստատին", "ru": "Аторвастатин", "en": "Atorvastatin",
     "desc": {"en": "Statin.", "ru": "Статин.", "hy": "Ստատին։"},
     "ind": {"en": "Hypercholesterolemia.", "ru": "Гиперхолестеринемия.", "hy": "Հիպերխոլեստերինեմիա։"},
     "side": ["Muscle pain"], "contra": ["Liver disease"],
     "dosages": ["10 mg", "20 mg", "40 mg", "80 mg"], "forms": ["tablet"]},
    {"sub": "Rosuvastatin", "cat": "cardio",
     "hy": "Ռոզուվաստատին", "ru": "Розувастатин", "en": "Rosuvastatin",
     "desc": {"en": "Statin.", "ru": "Статин.", "hy": "Ստատին։"},
     "ind": {"en": "Hypercholesterolemia.", "ru": "Гиперхолестеринемия.", "hy": "Խոլեստերին։"},
     "side": ["Myalgia"], "contra": ["Liver disease"],
     "dosages": ["5 mg", "10 mg", "20 mg", "40 mg"], "forms": ["tablet"]},
    {"sub": "Enalapril", "cat": "cardio",
     "hy": "Էնալապրիլ", "ru": "Эналаприл", "en": "Enalapril",
     "desc": {"en": "ACE inhibitor.", "ru": "Ингибитор АПФ.", "hy": "ԱՊՖ։"},
     "ind": {"en": "Hypertension.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Dry cough"], "contra": ["Pregnancy"],
     "dosages": ["5 mg", "10 mg", "20 mg"], "forms": ["tablet"]},
    {"sub": "Valsartan", "cat": "cardio",
     "hy": "Վալսարտան", "ru": "Валсартан", "en": "Valsartan",
     "desc": {"en": "ARB.", "ru": "БРА.", "hy": "ԱԲ։"},
     "ind": {"en": "Hypertension.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Dizziness"], "contra": ["Pregnancy"],
     "dosages": ["40 mg", "80 mg", "160 mg"], "forms": ["tablet"]},
    {"sub": "Metoprolol", "cat": "cardio",
     "hy": "Մետոպրոլոլ", "ru": "Метопролол", "en": "Metoprolol",
     "desc": {"en": "Beta-blocker.", "ru": "Бета-блокатор.", "hy": "Բետա-բլոկատոր։"},
     "ind": {"en": "Hypertension, angina.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Fatigue"], "contra": ["AV block"],
     "dosages": ["25 mg", "50 mg", "100 mg"], "forms": ["tablet"]},
    {"sub": "Clopidogrel", "cat": "cardio",
     "hy": "Կլոպիդոգրել", "ru": "Клопидогрел", "en": "Clopidogrel",
     "desc": {"en": "Antiplatelet.", "ru": "Антиагрегант.", "hy": "Հակաթրոմբոցիտային։"},
     "ind": {"en": "Post-MI, stroke prevention.", "ru": "После ИМ.", "hy": "Հետ ինֆարկտային։"},
     "side": ["Bleeding"], "contra": ["Active bleeding"],
     "dosages": ["75 mg"], "forms": ["tablet"]},
    {"sub": "Warfarin", "cat": "cardio",
     "hy": "Վարֆարին", "ru": "Варфарин", "en": "Warfarin",
     "desc": {"en": "Anticoagulant.", "ru": "Антикоагулянт.", "hy": "Հակամակարդիչ։"},
     "ind": {"en": "Anticoagulation.", "ru": "Антикоагуляция.", "hy": "Հակամակարդում։"},
     "side": ["Bleeding"], "contra": ["Pregnancy"],
     "dosages": ["2.5 mg", "5 mg"], "forms": ["tablet"]},
    {"sub": "Furosemide", "cat": "cardio",
     "hy": "Ֆուրոսեմիդ", "ru": "Фуросемид", "en": "Furosemide",
     "desc": {"en": "Loop diuretic.", "ru": "Петлевой диуретик.", "hy": "Միզամուղ։"},
     "ind": {"en": "Edema.", "ru": "Отёки.", "hy": "Այտուց։"},
     "side": ["Electrolyte loss"], "contra": ["Anuria"],
     "dosages": ["20 mg", "40 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Indapamide", "cat": "cardio",
     "hy": "Ինդապամիդ", "ru": "Индапамид", "en": "Indapamide",
     "desc": {"en": "Diuretic.", "ru": "Диуретик.", "hy": "Միզամուղ։"},
     "ind": {"en": "Hypertension.", "ru": "Гипертония.", "hy": "Հիպերտոնիա։"},
     "side": ["Hypokalemia"], "contra": ["Anuria"],
     "dosages": ["1.5 mg", "2.5 mg"], "forms": ["tablet"]},
    {"sub": "Nitroglycerin", "cat": "cardio",
     "hy": "Նիտրոգլիցերին", "ru": "Нитроглицерин", "en": "Nitroglycerin",
     "desc": {"en": "Nitrate vasodilator.", "ru": "Нитрат.", "hy": "Նիտրատ։"},
     "ind": {"en": "Angina.", "ru": "Стенокардия.", "hy": "Ստենոկարդիա։"},
     "side": ["Headache"], "contra": ["Severe hypotension"],
     "dosages": ["0.5 mg"], "forms": ["sublingual tablet", "spray"]},

    # Gastro
    {"sub": "Omeprazole", "cat": "gastro",
     "hy": "Օմեպրազոլ", "ru": "Омепразол", "en": "Omeprazole",
     "desc": {"en": "PPI.", "ru": "ИПП.", "hy": "ՊՊԻ։"},
     "ind": {"en": "GERD, ulcers.", "ru": "ГЭРБ.", "hy": "ԳԷՌՀ։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["10 mg", "20 mg", "40 mg"], "forms": ["capsule"]},
    {"sub": "Pantoprazole", "cat": "gastro",
     "hy": "Պանտոպրազոլ", "ru": "Пантопразол", "en": "Pantoprazole",
     "desc": {"en": "PPI.", "ru": "ИПП.", "hy": "ՊՊԻ։"},
     "ind": {"en": "GERD.", "ru": "ГЭРБ.", "hy": "ԳԷՌՀ։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["20 mg", "40 mg"], "forms": ["tablet"]},
    {"sub": "Esomeprazole", "cat": "gastro",
     "hy": "Էզոմեպրազոլ", "ru": "Эзомепразол", "en": "Esomeprazole",
     "desc": {"en": "PPI.", "ru": "ИПП.", "hy": "ՊՊԻ։"},
     "ind": {"en": "GERD.", "ru": "ГЭРБ.", "hy": "ԳԷՌՀ։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["20 mg", "40 mg"], "forms": ["tablet"]},
    {"sub": "Ranitidine", "cat": "gastro",
     "hy": "Ռանիտիդին", "ru": "Ранитидин", "en": "Ranitidine",
     "desc": {"en": "H2-blocker.", "ru": "H2-блокатор.", "hy": "H2-բլոկատոր։"},
     "ind": {"en": "Ulcer.", "ru": "Язва.", "hy": "Խոց։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["75 mg", "150 mg"], "forms": ["tablet"]},
    {"sub": "Loperamide", "cat": "gastro",
     "hy": "Լոպերամիդ", "ru": "Лоперамид", "en": "Loperamide",
     "desc": {"en": "Antidiarrheal.", "ru": "Противодиарейное.", "hy": "Հակալուծային։"},
     "ind": {"en": "Diarrhea.", "ru": "Диарея.", "hy": "Լուծ։"},
     "side": ["Constipation"], "contra": ["Children <6"],
     "dosages": ["2 mg"], "forms": ["capsule"]},
    {"sub": "Domperidone", "cat": "gastro",
     "hy": "Դոմպերիդոն", "ru": "Домперидон", "en": "Domperidone",
     "desc": {"en": "Prokinetic.", "ru": "Прокинетик.", "hy": "Պրոկինետիկ։"},
     "ind": {"en": "Nausea, vomiting.", "ru": "Тошнота.", "hy": "Սրտխառնոց։"},
     "side": ["QT prolongation"], "contra": ["Cardiac arrhythmia"],
     "dosages": ["10 mg"], "forms": ["tablet"]},
    {"sub": "Metoclopramide", "cat": "gastro",
     "hy": "Մետոկլոպրամիդ", "ru": "Метоклопрамид", "en": "Metoclopramide",
     "desc": {"en": "Antiemetic.", "ru": "Противорвотное.", "hy": "Հակափսխող։"},
     "ind": {"en": "Nausea.", "ru": "Тошнота.", "hy": "Սրտխառնոց։"},
     "side": ["Extrapyramidal effects"], "contra": ["Pheochromocytoma"],
     "dosages": ["10 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Simethicone", "cat": "gastro",
     "hy": "Սիմետիկոն", "ru": "Симетикон", "en": "Simethicone",
     "desc": {"en": "Antiflatulent.", "ru": "Ветрогонное.", "hy": "Հակափքվածքային։"},
     "ind": {"en": "Bloating.", "ru": "Метеоризм.", "hy": "Փքվածք։"},
     "side": ["None notable"], "contra": ["Hypersensitivity"],
     "dosages": ["40 mg", "80 mg"], "forms": ["capsule", "drops"]},
    {"sub": "Smecta", "cat": "gastro",
     "hy": "Սմեկտա", "ru": "Смекта", "en": "Diosmectite",
     "desc": {"en": "Intestinal adsorbent.", "ru": "Энтеросорбент.", "hy": "Աղիքային ադսորբենտ։"},
     "ind": {"en": "Diarrhea.", "ru": "Диарея.", "hy": "Լուծ։"},
     "side": ["Constipation"], "contra": ["Intestinal obstruction"],
     "dosages": ["3 g"], "forms": ["powder"]},
    {"sub": "Mesalazine", "cat": "gastro",
     "hy": "Մեսալազին", "ru": "Месалазин", "en": "Mesalazine",
     "desc": {"en": "Anti-inflammatory for IBD.", "ru": "ВЗК.", "hy": "ՎԶԿ։"},
     "ind": {"en": "Ulcerative colitis.", "ru": "Колит.", "hy": "Կոլիտ։"},
     "side": ["Diarrhea"], "contra": ["Hypersensitivity"],
     "dosages": ["500 mg", "1000 mg"], "forms": ["tablet", "suppository"]},

    # Diabetes
    {"sub": "Metformin", "cat": "diabetes",
     "hy": "Մետֆորմին", "ru": "Метформин", "en": "Metformin",
     "desc": {"en": "Biguanide.", "ru": "Бигуанид.", "hy": "Բիգուանիդ։"},
     "ind": {"en": "Type 2 diabetes.", "ru": "СД 2 типа.", "hy": "Շաքարային դիաբետ 2։"},
     "side": ["GI upset"], "contra": ["Renal failure"],
     "dosages": ["500 mg", "850 mg", "1000 mg"], "forms": ["tablet"]},
    {"sub": "Gliclazide", "cat": "diabetes",
     "hy": "Գլիկլազիդ", "ru": "Гликлазид", "en": "Gliclazide",
     "desc": {"en": "Sulfonylurea.", "ru": "Сульфонилмочевина.", "hy": "Սուլֆոնիլուրեա։"},
     "ind": {"en": "Type 2 diabetes.", "ru": "СД 2.", "hy": "ՇԴ 2։"},
     "side": ["Hypoglycemia"], "contra": ["Type 1 diabetes"],
     "dosages": ["30 mg", "60 mg", "80 mg"], "forms": ["tablet"]},
    {"sub": "Insulin glargine", "cat": "diabetes",
     "hy": "Ինսուլին գլարգին", "ru": "Инсулин гларгин", "en": "Insulin glargine",
     "desc": {"en": "Long-acting insulin.", "ru": "Инсулин длительного действия.", "hy": "Երկարատև ինսուլին։"},
     "ind": {"en": "Diabetes.", "ru": "СД.", "hy": "ՇԴ։"},
     "side": ["Hypoglycemia"], "contra": ["Hypoglycemia"],
     "dosages": ["100 U/ml"], "forms": ["solution"]},
    {"sub": "Sitagliptin", "cat": "diabetes",
     "hy": "Սիտագլիպտին", "ru": "Ситаглиптин", "en": "Sitagliptin",
     "desc": {"en": "DPP-4 inhibitor.", "ru": "ДПП-4 ингибитор.", "hy": "ԴՊՊ-4։"},
     "ind": {"en": "Type 2 diabetes.", "ru": "СД 2.", "hy": "ՇԴ 2։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["25 mg", "50 mg", "100 mg"], "forms": ["tablet"]},

    # Respiratory
    {"sub": "Salbutamol", "cat": "respiratory",
     "hy": "Սալբուտամոլ", "ru": "Сальбутамол", "en": "Salbutamol",
     "desc": {"en": "Short-acting beta-2 agonist.", "ru": "Бета-2 агонист.", "hy": "Բետա-2 ագոնիստ։"},
     "ind": {"en": "Asthma.", "ru": "Астма.", "hy": "Ասթմա։"},
     "side": ["Tremor"], "contra": ["Hypersensitivity"],
     "dosages": ["100 mcg"], "forms": ["inhaler", "nebulizer"]},
    {"sub": "Budesonide", "cat": "respiratory",
     "hy": "Բուդեսոնիդ", "ru": "Будесонид", "en": "Budesonide",
     "desc": {"en": "Inhaled corticosteroid.", "ru": "ИГКС.", "hy": "ԻԳԿՍ։"},
     "ind": {"en": "Asthma.", "ru": "Астма.", "hy": "Ասթմա։"},
     "side": ["Oral candidiasis"], "contra": ["Active TB"],
     "dosages": ["100 mcg", "200 mcg"], "forms": ["inhaler"]},
    {"sub": "Montelukast", "cat": "respiratory",
     "hy": "Մոնտելուկաստ", "ru": "Монтелукаст", "en": "Montelukast",
     "desc": {"en": "Leukotriene receptor antagonist.", "ru": "Антагонист лейкотриенов.", "hy": "Լեյկոտրիեն։"},
     "ind": {"en": "Asthma.", "ru": "Астма.", "hy": "Ասթմա։"},
     "side": ["Headache"], "contra": ["Hypersensitivity"],
     "dosages": ["4 mg", "5 mg", "10 mg"], "forms": ["tablet", "chewable"]},

    # Nervous / mental
    {"sub": "Diazepam", "cat": "nervous",
     "hy": "Դիազեպամ", "ru": "Диазепам", "en": "Diazepam",
     "desc": {"en": "Benzodiazepine.", "ru": "Бензодиазепин.", "hy": "Բենզոդիազեպին։"},
     "ind": {"en": "Anxiety, seizures.", "ru": "Тревога.", "hy": "Անհանգստություն։"},
     "side": ["Drowsiness"], "contra": ["Myasthenia gravis"],
     "dosages": ["2 mg", "5 mg", "10 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Sertraline", "cat": "nervous",
     "hy": "Սերտրալին", "ru": "Сертралин", "en": "Sertraline",
     "desc": {"en": "SSRI antidepressant.", "ru": "СИОЗС.", "hy": "ՍԻՈԶՍ։"},
     "ind": {"en": "Depression, anxiety.", "ru": "Депрессия.", "hy": "Դեպրեսիա։"},
     "side": ["Nausea"], "contra": ["MAOI co-administration"],
     "dosages": ["25 mg", "50 mg", "100 mg"], "forms": ["tablet"]},
    {"sub": "Amitriptyline", "cat": "nervous",
     "hy": "Ամիտրիպտիլին", "ru": "Амитриптилин", "en": "Amitriptyline",
     "desc": {"en": "Tricyclic antidepressant.", "ru": "Трицикл. антидепрессант.", "hy": "Տրիցիկլիկ։"},
     "ind": {"en": "Depression.", "ru": "Депрессия.", "hy": "Դեպրեսիա։"},
     "side": ["Dry mouth"], "contra": ["Recent MI"],
     "dosages": ["10 mg", "25 mg"], "forms": ["tablet"]},
    {"sub": "Phenobarbital", "cat": "nervous",
     "hy": "Ֆենոբարբիտալ", "ru": "Фенобарбитал", "en": "Phenobarbital",
     "desc": {"en": "Barbiturate.", "ru": "Барбитурат.", "hy": "Բարբիտուրատ։"},
     "ind": {"en": "Epilepsy.", "ru": "Эпилепсия.", "hy": "Էպիլեպսիա։"},
     "side": ["Drowsiness"], "contra": ["Severe liver disease"],
     "dosages": ["50 mg", "100 mg"], "forms": ["tablet"]},
    {"sub": "Carbamazepine", "cat": "nervous",
     "hy": "Կարբամազեպին", "ru": "Карбамазепин", "en": "Carbamazepine",
     "desc": {"en": "Anticonvulsant.", "ru": "Антиконвульсант.", "hy": "Հակացնցումային։"},
     "ind": {"en": "Epilepsy.", "ru": "Эпилепсия.", "hy": "Էպիլեպսիա։"},
     "side": ["Dizziness"], "contra": ["AV block"],
     "dosages": ["200 mg", "400 mg"], "forms": ["tablet"]},

    # Hormonal
    {"sub": "Levothyroxine", "cat": "hormonal",
     "hy": "Լևոթիրօքսին", "ru": "Левотироксин", "en": "Levothyroxine",
     "desc": {"en": "Thyroid hormone.", "ru": "Гормон щитовидной железы.", "hy": "Վահանաձև գեղձ։"},
     "ind": {"en": "Hypothyroidism.", "ru": "Гипотиреоз.", "hy": "Հիպոթիրեոզ։"},
     "side": ["Tachycardia at overdose"], "contra": ["Untreated adrenal insufficiency"],
     "dosages": ["25 mcg", "50 mcg", "75 mcg", "100 mcg"], "forms": ["tablet"]},
    {"sub": "Prednisolone", "cat": "hormonal",
     "hy": "Պրեդնիզոլոն", "ru": "Преднизолон", "en": "Prednisolone",
     "desc": {"en": "Glucocorticoid.", "ru": "Глюкокортикоид.", "hy": "Գլյուկոկորտիկոիդ։"},
     "ind": {"en": "Inflammation.", "ru": "Воспаление.", "hy": "Բորբոքում։"},
     "side": ["Cushing syndrome"], "contra": ["Systemic fungal infection"],
     "dosages": ["5 mg", "20 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Hydrocortisone", "cat": "hormonal",
     "hy": "Հիդրոկորտիզոն", "ru": "Гидрокортизон", "en": "Hydrocortisone",
     "desc": {"en": "Corticosteroid.", "ru": "Кортикостероид.", "hy": "Կորտիկոստերոիդ։"},
     "ind": {"en": "Inflammation.", "ru": "Воспаление.", "hy": "Բորբոքում։"},
     "side": ["Skin atrophy"], "contra": ["Viral skin infection"],
     "dosages": ["1%", "2.5%"], "forms": ["cream", "ointment"]},
    {"sub": "Estradiol", "cat": "hormonal",
     "hy": "Էստրադիոլ", "ru": "Эстрадиол", "en": "Estradiol",
     "desc": {"en": "Estrogen.", "ru": "Эстроген.", "hy": "Էստրոգեն։"},
     "ind": {"en": "Menopause symptoms.", "ru": "Менопауза.", "hy": "Մենոպաուզա։"},
     "side": ["Breast tenderness"], "contra": ["Breast cancer"],
     "dosages": ["1 mg", "2 mg"], "forms": ["tablet", "patch"]},

    # Antiseptics
    {"sub": "Chlorhexidine", "cat": "antiseptics",
     "hy": "Քլորհեքսիդին", "ru": "Хлоргексидин", "en": "Chlorhexidine",
     "desc": {"en": "Topical antiseptic.", "ru": "Антисептик.", "hy": "Հակասեպտիկ։"},
     "ind": {"en": "Skin/mucosa disinfection.", "ru": "Дезинфекция.", "hy": "Ախտահանում։"},
     "side": ["Local irritation"], "contra": ["Hypersensitivity"],
     "dosages": ["0.05%", "0.2%"], "forms": ["solution", "gel"]},
    {"sub": "Povidone-iodine", "cat": "antiseptics",
     "hy": "Բետադին", "ru": "Бетадин", "en": "Povidone-iodine",
     "desc": {"en": "Topical antiseptic.", "ru": "Антисептик.", "hy": "Հակասեպտիկ։"},
     "ind": {"en": "Wound antisepsis.", "ru": "Раны.", "hy": "Վերքեր։"},
     "side": ["Local irritation"], "contra": ["Iodine hypersensitivity"],
     "dosages": ["10%"], "forms": ["solution", "ointment"]},
    {"sub": "Miramistin", "cat": "antiseptics",
     "hy": "Միրամիստին", "ru": "Мирамистин", "en": "Miramistin",
     "desc": {"en": "Antiseptic.", "ru": "Антисептик.", "hy": "Հակասեպտիկ։"},
     "ind": {"en": "Wounds, mucosa.", "ru": "Раны.", "hy": "Վերքեր։"},
     "side": ["Burning sensation"], "contra": ["Hypersensitivity"],
     "dosages": ["0.01%"], "forms": ["solution"]},

    # Antispasmodics
    {"sub": "Drotaverine", "cat": "antispasmodics",
     "hy": "Դրոտավերին", "ru": "Дротаверин", "en": "Drotaverine",
     "desc": {"en": "Antispasmodic.", "ru": "Спазмолитик.", "hy": "Հակասպազմոդիկ։"},
     "ind": {"en": "Smooth muscle spasm.", "ru": "Спазм.", "hy": "Սպազմ։"},
     "side": ["Hypotension"], "contra": ["Severe heart failure"],
     "dosages": ["40 mg", "80 mg"], "forms": ["tablet", "injection"]},
    {"sub": "Hyoscine butylbromide", "cat": "antispasmodics",
     "hy": "Բուսկոպան", "ru": "Бускопан", "en": "Hyoscine butylbromide",
     "desc": {"en": "Antispasmodic.", "ru": "Спазмолитик.", "hy": "Հակասպազմոդիկ։"},
     "ind": {"en": "GI spasms.", "ru": "Спазм ЖКТ.", "hy": "ՍԱ սպազմ։"},
     "side": ["Dry mouth"], "contra": ["Glaucoma"],
     "dosages": ["10 mg"], "forms": ["tablet"]},
    {"sub": "Mebeverine", "cat": "antispasmodics",
     "hy": "Մեբեվերին", "ru": "Мебеверин", "en": "Mebeverine",
     "desc": {"en": "GI antispasmodic.", "ru": "Спазмолитик.", "hy": "Հակասպազմոդիկ։"},
     "ind": {"en": "Irritable bowel.", "ru": "СРК.", "hy": "ԳՇՍ։"},
     "side": ["Headache"], "contra": ["Paralytic ileus"],
     "dosages": ["135 mg", "200 mg"], "forms": ["tablet", "capsule"]},

    # Pediatric (paediatric-specific labelling)
    {"sub": "Nurofen for kids", "cat": "pediatric",
     "hy": "Նուրոֆեն մանկական", "ru": "Нурофен детский", "en": "Ibuprofen for children",
     "desc": {"en": "Pediatric ibuprofen suspension.", "ru": "Детский ибупрофен.", "hy": "Մանկական իբուպրոֆեն։"},
     "ind": {"en": "Fever, pain in children.", "ru": "Жар у детей.", "hy": "Ջերմություն երեխաների մոտ։"},
     "side": ["GI upset"], "contra": ["Age <3 months"],
     "dosages": ["100 mg/5ml"], "forms": ["suspension", "suppository"]},
    {"sub": "Panadol baby", "cat": "pediatric",
     "hy": "Պանադոլ մանկական", "ru": "Панадол беби", "en": "Paracetamol baby",
     "desc": {"en": "Pediatric paracetamol.", "ru": "Детский парацетамол.", "hy": "Մանկական պարացետամոլ։"},
     "ind": {"en": "Fever in babies.", "ru": "Жар у младенцев.", "hy": "Ջերմություն։"},
     "side": ["Rash"], "contra": ["Liver disease"],
     "dosages": ["120 mg/5ml", "250 mg/5ml"], "forms": ["suspension"]},
    {"sub": "ORS pediatric", "cat": "pediatric",
     "hy": "ՕՌՍ", "ru": "Регидрон", "en": "Oral rehydration salts",
     "desc": {"en": "Oral rehydration.", "ru": "Регидратация.", "hy": "Ռեհիդրատացիա։"},
     "ind": {"en": "Dehydration.", "ru": "Дегидратация.", "hy": "Ջրազրկում։"},
     "side": ["Nausea"], "contra": ["Renal failure"],
     "dosages": ["sachet"], "forms": ["powder"]},
]

# Manufacturers — 65 entries × 91 substances ≈ 5900 unique brand records.
MANUFACTURERS = [
    ("Liqvor", "Armenia"), ("Esperal", "Armenia"), ("Arpimed", "Armenia"),
    ("Pharmtechexpert", "Armenia"), ("Pharmacare", "Armenia"),
    ("Akhtamar Pharm", "Armenia"), ("Ararat Pharma", "Armenia"),
    ("Yerevan Bio", "Armenia"), ("Masis Pharma", "Armenia"),
    ("Bayer", "Germany"), ("Sanofi", "France"), ("Novartis", "Switzerland"),
    ("Pfizer", "USA"), ("GSK", "UK"), ("KRKA", "Slovenia"),
    ("Gedeon Richter", "Hungary"), ("Egis", "Hungary"), ("Teva", "Israel"),
    ("Servier", "France"), ("Berlin-Chemie", "Germany"),
    ("Stada", "Germany"), ("Lek", "Slovenia"), ("Boehringer Ingelheim", "Germany"),
    ("Mylan", "USA"), ("Sandoz", "Switzerland"), ("Actavis", "Iceland"),
    ("Hemofarm", "Serbia"), ("Polpharma", "Poland"), ("Zentiva", "Czech Republic"),
    ("Bosnalijek", "Bosnia"), ("Pliva", "Croatia"), ("Adamed", "Poland"),
    ("Galenika", "Serbia"), ("Sopharma", "Bulgaria"), ("Actiphar", "Belgium"),
    ("Krka Novo Mesto", "Slovenia"), ("Reckitt Benckiser", "UK"),
    ("Johnson and Johnson", "USA"), ("AbbVie", "USA"), ("Merck", "Germany"),
    ("Roche", "Switzerland"), ("AstraZeneca", "UK"), ("Eli Lilly", "USA"),
    ("Bristol-Myers", "USA"), ("Takeda", "Japan"), ("Astellas", "Japan"),
    ("Daiichi Sankyo", "Japan"), ("Sun Pharma", "India"),
    ("Dr Reddys", "India"), ("Cipla", "India"), ("Lupin", "India"),
    ("Glenmark", "India"), ("Torrent", "India"), ("Aurobindo", "India"),
    ("Sigma-Tau", "Italy"), ("Menarini", "Italy"), ("Recordati", "Italy"),
    ("Almirall", "Spain"), ("Grifols", "Spain"), ("Faes Farma", "Spain"),
    ("Pharmstandard", "Russia"), ("R-Pharm", "Russia"), ("Veropharm", "Russia"),
    ("Valenta", "Russia"), ("Nizhpharm", "Russia"),
]

_BRAND_TAG = {
    "Liqvor": "-Liq", "Esperal": "-Esp", "Arpimed": "-Arp", "Pharmtechexpert": "-PTE",
    "Pharmacare": "-PC", "Bayer": " Bayer", "Sanofi": " Sanofi", "Novartis": " Novartis",
    "Pfizer": " Pfizer", "GSK": " GSK", "KRKA": " KRKA", "Gedeon Richter": " GR",
    "Egis": " Egis", "Teva": " Teva", "Servier": " Serv", "Berlin-Chemie": " BC",
    "Stada": " Stada", "Lek": " Lek", "Boehringer Ingelheim": " BI",
    "Mylan": " Mylan", "Sandoz": " Sandoz", "Actavis": " Actavis",
    "Hemofarm": " HF", "Polpharma": " Pol", "Zentiva": " Zen",
}


def _tag_for(mfr: str) -> str:
    if mfr in _BRAND_TAG:
        return _BRAND_TAG[mfr]
    parts = mfr.replace("-", " ").replace(".", " ").split()
    initials = "".join(p[0].upper() for p in parts if p)[:4]
    return f" {initials}" if initials else f" {mfr[:3]}"


def _build():
    out: List[Dict] = []
    seen = set()
    for s in SUBSTANCES:
        for (mfr, country) in MANUFACTURERS:
            tag = _tag_for(mfr)
            forms = s.get("forms", ["tablet"])
            primary_form = forms[0]
            variants = []
            for d in s["dosages"]:
                for f in forms:
                    variants.append({"form": f, "dosage": d, "package_info": ""})
            primary_dosage = s["dosages"][0]
            name_en = f"{s['en']}{tag}"
            key = name_en.lower().strip()
            if key in seen:
                continue
            seen.add(key)
            rec = {
                "name_hy": f"{s['hy']}{tag}",
                "name_ru": f"{s['ru']}{tag}",
                "name_en": name_en,
                "active_substance": s["sub"],
                "form": primary_form,
                "dosage": primary_dosage,
                "manufacturer": mfr,
                "country": country,
                "category": s["cat"],
                "registered_in_am": 1,
                "image_url": "",
                "description": s["desc"],
                "indications": s["ind"],
                "symptoms": {},
                "side_effects": s["side"],
                "contraindications": s["contra"],
                "instruction": {"en": "Follow physician/pharmacist instructions.",
                                 "ru": "Согласно инструкции врача или фармацевта.",
                                 "hy": "Համաձայն բժշկի կամ դեղագործի հրահանգների։"},
                "variants": variants,
                "aliases": [s["en"], s["ru"], s["hy"], s["sub"]],
            }
            out.append(rec)
    return out


FALLBACK_MEDICINES: List[Dict] = _build()

# ---------------------------------------------------------------------------
# Pharmacy chains + branches (simplified UI: chains → branches list).
# ---------------------------------------------------------------------------
CHAINS = [
    {"key": "natali-pharm", "name": "Natali Pharm",
     "description_hy": "Հայաստանի խոշորագույն դեղատների ցանցերից մեկը։",
     "description_ru": "Одна из крупнейших аптечных сетей Армении.",
     "description_en": "One of Armenia's largest pharmacy chains.",
     "website": "https://natalipharm.am"},
    {"key": "alfa-pharm", "name": "Alfa Pharm",
     "description_hy": "Ժամանակակից դեղատների ցանց՝ լայն տեսականիով։",
     "description_ru": "Современная аптечная сеть с широким ассортиментом.",
     "description_en": "Modern pharmacy chain with a wide assortment.",
     "website": "https://alfapharm.am"},
    {"key": "pharmacy-36-6", "name": "36.6 Pharmacy",
     "description_hy": "Միջազգային ապրանքանիշ՝ ներկա Հայաստանում։",
     "description_ru": "Международный бренд, представленный в Армении.",
     "description_en": "International brand present in Armenia.",
     "website": ""},
    {"key": "viva-pharm", "name": "Viva Pharm",
     "description_hy": "Տեղական դեղատների ցանց՝ բոլորի համար մատչելի։",
     "description_ru": "Локальная сеть, доступная для всех.",
     "description_en": "Local affordable pharmacy chain.",
     "website": ""},
    {"key": "pharmacity", "name": "Pharmacity",
     "description_hy": "Քաղաքային ձևաչափի դեղատներ՝ 24/7 ծառայությամբ։",
     "description_ru": "Городские аптеки с режимом 24/7.",
     "description_en": "City-format pharmacies with 24/7 service.",
     "website": ""},
]

_CITIES = [
    "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan",
    "Hrazdan", "Armavir", "Artashat", "Ijevan", "Sevan", "Goris", "Dilijan",
    "Ashtarak", "Charentsavan", "Masis", "Artik",
]
_STREETS = [
    "Mashtots Ave.", "Tigran Mets Ave.", "Komitas Ave.", "Baghramyan Ave.",
    "Northern Ave.", "Sayat-Nova Ave.", "Abovyan St.", "Nalbandyan St.",
    "Khanjyan St.", "Saryan St.", "Aram St.", "Pushkin St.", "Teryan St.",
    "Heratsi St.", "Moskovyan St.", "Movses Khorenatsi St.",
]
_HOURS = ["09:00–21:00", "09:00–22:00", "08:00–22:00", "10:00–22:00", "24/7"]


def build_branches_for(chain_key: str):
    """Deterministic realistic Armenian branches per chain (12–18 branches)."""
    rng_seed = sum(ord(c) for c in chain_key)
    branches = []
    n = 12 + (rng_seed % 7)
    for i in range(n):
        city = _CITIES[(rng_seed + i * 3) % len(_CITIES)]
        street = _STREETS[(rng_seed + i * 5) % len(_STREETS)]
        num = ((rng_seed + i * 7) % 80) + 1
        hours = _HOURS[i % len(_HOURS)] if i != 0 else "09:00–21:00"
        a = 10 + ((rng_seed + i) % 90)
        b = 100000 + ((rng_seed * 31 + i * 17) % 899999)
        phone = f"+374 {a} {str(b)[:2]}-{str(b)[2:4]}-{str(b)[4:6]}"
        branches.append({
            "branch_name": f"{chain_key.split('-')[0].title()} #{i + 1}",
            "city": city,
            "address": f"{street} {num}, {city}",
            "phone": phone,
            "working_hours": hours,
            "status": "active",
        })
    return branches


PHARMACY_NAMES = PHARMACY_NAMES  # re-export

